name: "Build iOS+macOS app"

on:
  pull_request:
  push:

env:
  GO_VERSION: "~1.24.0"

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: |
          /usr/bin/xcodebuild -version
          sudo /usr/bin/xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
          /usr/bin/xcodebuild -version

      - name: Install iOS platform
        run: |
          xcodebuild -downloadPlatform iOS -buildVersion 18.2

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint
        run: |
          make lint

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
          check-latest: true

      - name: Build core
        run: |
          make core

      - name: Obtain certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        run: |
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o "./Assets/developer-certificate.p12"

      - name: Build for iOS and macOS
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          make ios mac
          make cleanup

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./Build
          retention-days: 3

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-path: ./Build/synctrain.ipa
